import { describe, it, expect } from 'vitest';
import { generateHtmlReport } from '../src/utils/htmlReport.js';
import type { ForgeReport, Grade } from '../src/types/index.js';

// ── Test Helpers ────────────────────────────────────────────────────

function makeReport(overrides: Partial<ForgeReport> = {}): ForgeReport {
  return {
    server: { command: 'node', args: ['server.js'] },
    timestamp: '2026-03-31T12:00:00Z',
    suites: [
      {
        suite: 'Protocol Tests',
        durationMs: 150,
        results: [
          { name: 'handshake', status: 'pass', severity: 'info', message: 'Connected successfully' },
          { name: 'version-check', status: 'fail', severity: 'critical', message: 'Version mismatch' },
          { name: 'optional-feature', status: 'warn', severity: 'medium', message: 'Feature deprecated' },
          { name: 'experimental', status: 'skip', severity: 'low', message: 'Not implemented' },
        ],
      },
    ],
    summary: {
      total: 4,
      passed: 1,
      failed: 1,
      warnings: 1,
      skipped: 1,
      durationMs: 150,
      grade: 'C',
    },
    ...overrides,
  };
}

// ── Tests ───────────────────────────────────────────────────────────

describe('generateHtmlReport', () => {
  it('should return valid HTML with DOCTYPE', () => {
    const html = generateHtmlReport(makeReport());
    expect(html).toMatch(/^<!DOCTYPE html>/);
    expect(html).toContain('<html');
    expect(html).toContain('</html>');
    expect(html).toContain('<head>');
    expect(html).toContain('<body>');
  });

  it('should include the grade in the output', () => {
    const html = generateHtmlReport(makeReport({ summary: { ...makeReport().summary, grade: 'B' } }));
    expect(html).toContain('grade-b');
    expect(html).toContain('>B<');
  });

  it('should include suite names', () => {
    const html = generateHtmlReport(makeReport());
    expect(html).toContain('Protocol Tests');
  });

  it('should include test result messages', () => {
    const html = generateHtmlReport(makeReport());
    expect(html).toContain('Connected successfully');
    expect(html).toContain('Version mismatch');
    expect(html).toContain('Feature deprecated');
    expect(html).toContain('Not implemented');
  });

  it('should handle empty suites', () => {
    const report = makeReport({
      suites: [{ suite: 'Empty Suite', results: [], durationMs: 0 }],
    });
    const html = generateHtmlReport(report);
    expect(html).toContain('Empty Suite');
    expect(html).toContain('No tests in this suite');
  });

  it('should assign the correct color class for each grade', () => {
    const grades: readonly Grade[] = ['A', 'B', 'C', 'D', 'F'] as const;
    const expectedClasses: Record<Grade, string> = {
      A: 'grade-a',
      B: 'grade-b',
      C: 'grade-c',
      D: 'grade-d',
      F: 'grade-f',
    };

    for (const grade of grades) {
      const report = makeReport({ summary: { ...makeReport().summary, grade } });
      const html = generateHtmlReport(report);
      expect(html).toContain(expectedClasses[grade]);
    }
  });

  it('should render status badges with correct CSS classes', () => {
    const html = generateHtmlReport(makeReport());
    expect(html).toContain('status-pass');
    expect(html).toContain('status-fail');
    expect(html).toContain('status-warn');
    expect(html).toContain('status-skip');
  });

  it('should include footer with timestamp and generator', () => {
    const html = generateHtmlReport(makeReport());
    expect(html).toContain('2026-03-31T12:00:00Z');
    expect(html).toContain('Generated by mcp-mint');
  });

  it('should contain a style tag with all CSS inlined', () => {
    const html = generateHtmlReport(makeReport());
    expect(html).toContain('<style>');
    expect(html).toContain('prefers-color-scheme: dark');
  });

  it('should include summary stats in the output', () => {
    const html = generateHtmlReport(makeReport());
    expect(html).toContain('Passed');
    expect(html).toContain('Failed');
    expect(html).toContain('Warnings');
    expect(html).toContain('Skipped');
    expect(html).toContain('Duration');
  });

  it('should format duration in seconds when >= 1000ms', () => {
    const report = makeReport({ summary: { ...makeReport().summary, durationMs: 2500 } });
    const html = generateHtmlReport(report);
    expect(html).toContain('2.50s');
  });

  it('should format duration in ms when < 1000ms', () => {
    const html = generateHtmlReport(makeReport());
    expect(html).toContain('150ms');
  });

  it('should escape HTML in user-provided strings', () => {
    const report = makeReport({
      suites: [{
        suite: '<script>alert("xss")</script>',
        durationMs: 10,
        results: [{
          name: 'test<>&"\'',
          status: 'pass',
          severity: 'info',
          message: 'msg<>&"\'',
        }],
      }],
    });
    const html = generateHtmlReport(report);
    expect(html).not.toContain('<script>alert');
    expect(html).toContain('&lt;script&gt;');
  });
});
